version: 2.1
orbs:
  architect: giantswarm/architect@4.8.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push flux-app chart"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "flux-app"
          persist_chart_archive: true
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests - smoke and functional
          additional_app-test-suite_flags: "--skip-steps upgrade"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - "package and push flux-app chart"

      - hold:
          type: approval
          requires:
           - "execute chart tests - smoke and functional"
      - deploy:
          name: execute chart tests - upgrade
          additional_app-test-suite_flags: "--skip-steps smoke functional"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - hold
