{{- if or (.Capabilities.APIVersions.Has "cilium.io/v2/CiliumNetworkPolicy") (eq .Values.cilium.enforce true) }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "name" . }}-access-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  egress:
    - toEntities:
        - kube-apiserver
        - cluster
        - world
  ingress:
    - fromEntities:
        - kube-apiserver
        - cluster
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "name" . }}
{{- end }}
