{{- if .Values.podMonitors.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kustomize-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: {{ .Values.upstreamMetricsPort }}
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
          targetLabel: app
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
        - action: replace
          sourceLabels:
            - __meta_kubernetes_node_label_role
          targetLabel: role
  selector:
    matchLabels:
      app: kustomize-controller
{{ end }}
