---
apiVersion: v1
kind: Service
metadata:
  annotations:
    giantswarm.io/monitoring-path: /metrics
    giantswarm.io/monitoring-port: "8080"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Release.Name  }}-monitoring
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: 8080
      protocol: TCP
      targetPort: {{ .Values.upstreamMetricsPort }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
