---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "labels.common" . | indent 4}}
  name: crd-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-controller
subjects:
  - kind: ServiceAccount
    name: kustomize-controller
    namespace: "{{ .Release.Namespace }}"
  - kind: ServiceAccount
    name: helm-controller
    namespace: "{{ .Release.Namespace }}"
  - kind: ServiceAccount
    name: source-controller
    namespace: "{{ .Release.Namespace }}"
  - kind: ServiceAccount
    name: notification-controller
    namespace: "{{ .Release.Namespace }}"
  - kind: ServiceAccount
    name: image-reflector-controller
    namespace: "{{ .Release.Namespace }}"
  - kind: ServiceAccount
    name: image-automation-controller
    namespace: "{{ .Release.Namespace }}"
