{{- if .Values.clusterRoles.install }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{ include "labels.common" . | indent 4}}
  name: "flux-edit-{{ .Release.Name }}"
rules:
  - apiGroups:
      - notification.toolkit.fluxcd.io
      - source.toolkit.fluxcd.io
      - helm.toolkit.fluxcd.io
      - image.toolkit.fluxcd.io
      - kustomize.toolkit.fluxcd.io
    resources:
      - '*'
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
{{- end }}
