---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "labels.common" . | indent 4}}
  name: cluster-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kustomize-controller
    namespace: "{{ .Release.Namespace }}"
  - kind: ServiceAccount
    name: helm-controller
    namespace: "{{ .Release.Namespace }}"
