---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kustomize-controller
{{ include "labels.common" . | indent 4 }}
  name: kustomize-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/name: {{ include "name" . }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        {{ include "podTemplateLabels.kustomizeController" . }}
    spec:
      containers:
        - args:
            - --events-addr=http://notification-controller.{{ .Release.Namespace }}.svc.cluster.local./
            - --watch-all-namespaces
            - --log-level=info
            - --log-encoding=json
            - --enable-leader-election
          env:
            - name: RUNTIME_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: '{{ .Values.images.registry }}/{{ .Values.images.kustomizeController.image }}:v1.2.0'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          name: manager
          ports:
            - containerPort: 8080
              name: http-prom
              protocol: TCP
            - containerPort: 9440
              name: healthz
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          resources:
{{ include "resources.kustomizeController" . | indent 12 }}
          securityContext:
            {{- with .Values.containerSecurityContext }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
            readOnlyRootFilesystem: true
            runAsUser: 100
            {{- if ge (int .Capabilities.KubeVersion.Minor) 19 }}
            {{- with .Values.seccompProfile }}
            seccompProfile:
              {{- . | toYaml | nindent 14 }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: temp
      priorityClassName: {{ include "priorityClass.name" . }}
      securityContext:
        fsGroup: 1337
        {{- if ge (int .Capabilities.KubeVersion.Minor) 19 }}
        {{- with .Values.podSeccompProfile }}
        seccompProfile:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
      serviceAccountName: kustomize-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - emptyDir: {}
          name: temp
