---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
{{ include "labels.common" . | indent 4 }}
  name: allow-webhooks
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
    - from:
        - namespaceSelector: {}
  podSelector:
    matchLabels:
      app.kubernetes.io/component: notification-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/name: {{ include "name" . }}
  policyTypes:
    - Ingress
