---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
{{ include "labels.common" . | indent 4 }}
  name: allow-egress
  namespace: {{ .Release.Namespace }}
spec:
  egress:
    - {}
  ingress:
    - from:
        - podSelector: {}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/name: {{ include "name" . }}
  policyTypes:
    - Ingress
    - Egress
