---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
{{ include "labels.common" . | indent 4 }}
  name: allow-scraping
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - port: 8080
          protocol: TCP
  podSelector: {}
  policyTypes:
    - Ingress
