---
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
{{ include "labels.common" . | indent 4 }}
  name: critical-pods
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    pods: "1000"
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          - system-node-critical
          - system-cluster-critical
