---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: source-controller
{{ include "labels.common" . | indent 4 }}
  name: source-controller
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: source-controller
{{ include "labels.selector" . | indent 4 }}
  type: ClusterIP
