---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: source-watcher
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    control-plane: source-watcher
  name: source-watcher
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: source-watcher
  type: ClusterIP
