apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "{{ .Release.Namespace }}"

transformers:
# comment labels and matchlabels transformers out for crds
- ./labels-transformer.yaml
- ./matchlabels-transformer.yaml

images:
- name: fluxcd/helm-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.helm_controller.image }}"
- name: fluxcd/kustomize-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.kustomize_controller.image }}"
- name: fluxcd/source-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.source_controller.image }}"
- name: fluxcd/notification-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.notification_controller.image }}"
- name: fluxcd/image-automation-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.image_automation_controller.image }}"
- name: fluxcd/image-reflector-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.image_reflector_controller.image }}"


resources:
- https://github.com/fluxcd/flux2/releases/download/v0.5.9/install.yaml
