apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "{{ .Release.Namespace }}"

transformers:
# comment labels and matchlabels transformers out for crds
 - ./labels-transformer.yaml
 - ./matchlabels-transformer.yaml

images:
- name: ghcr.io/fluxcd/helm-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.helmController.image }}"
- name: ghcr.io/fluxcd/kustomize-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.kustomizeController.image }}"
- name: ghcr.io/fluxcd/source-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.sourceController.image }}"
- name: ghcr.io/fluxcd/notification-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.notificationController.image }}"
- name: ghcr.io/fluxcd/image-automation-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.imageAutomationController.image }}"
- name: ghcr.io/fluxcd/image-reflector-controller
  newName: "{{ .Values.images.registry }}/{{ .Values.images.imageReflectorController.image }}"


resources:
- https://github.com/fluxcd/flux2/releases/download/v0.41.2/install.yaml
- ./additional-resources/pvc-psp.yaml
- ./additional-resources/metrics-service.yaml

patches:
- path: ./patches/allow-scraping-networkpolicy-patch.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: NetworkPolicy
    name: allow-scraping
- path: ./patches/helm-controller-deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: helm-controller
- path: ./patches/image-automation-controller-deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: image-automation-controller
- path: ./patches/image-reflector-controller-deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: image-reflector-controller
- path: ./patches/kustomize-controller-deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: kustomize-controller
- path: ./patches/notification-controller-deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: notification-controller
- path: ./patches/source-controller-deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: source-controller
- path: ./patches/crd-controller-cluster-role-patch.yaml
  target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: crd-controller
    labelSelector: "app.kubernetes.io/instance=flux-system"
- path: ./patches/controller-securitycontext-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    labelSelector: "app.kubernetes.io/instance=flux-system"
- path: ./patches/all-deployments-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
