apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels-transformer
labels:
  app.kubernetes.io/name: '{{ include "name" . }}'
  app.kubernetes.io/instance: '{{ .Release.Name }}'
  app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  giantswarm.io/service_type: 'managed'
  helm.sh/chart: '{{ include "chart" . }}'
# fieldSpecs from https://github.com/kubernetes-sigs/kustomize/blob/a3bf3ba/api/konfig/builtinpluginconsts/commonlabels.go
# but omits any `matchLabels`. These are handeled by matchlabels-transformer.yaml
# update if neccessary!
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/selector
  create: true
  version: v1
  kind: ReplicationController
- path: spec/template/metadata/labels
  create: true
  version: v1
  kind: ReplicationController
- path: spec/template/metadata/labels
  create: true
  kind: Deployment
- path: spec/template/metadata/labels
  create: true
  kind: ReplicaSet
- path: spec/template/metadata/labels
  create: true
  kind: DaemonSet
- path: spec/template/metadata/labels
  create: true
  group: apps
  kind: StatefulSet
- path: spec/volumeClaimTemplates[]/metadata/labels
  create: true
  group: apps
  kind: StatefulSet
- path: spec/template/metadata/labels
  create: true
  group: batch
  kind: Job
- path: spec/jobTemplate/metadata/labels
  create: true
  group: batch
  kind: CronJob
- path: spec/jobTemplate/spec/template/metadata/labels
  create: true
  group: batch
  kind: CronJob
