{{ $globalScope := . }}
{{- range .Values.kustomizations }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crInstall" $globalScope }}-kustomization-{{ .name }}
  namespace: {{ $globalScope.Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    # TODO
    "helm.sh/hook-weight": "7"
    {{- include "crInstallAnnotations" $globalScope | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "crInstall" $globalScope | quote }}
    {{- include "labels.selector" $globalScope | nindent 4 }}
    role: {{ include "crInstallSelector" $globalScope | quote }}
data:
  content: |
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    metadata:
      name: "{{ .name }}"
      namespace: "{{ $globalScope.Release.Namespace }}"
    spec:
      interval: "{{ .interval }}"
      path: "{{ .path }}"
      {{- if .postBuild }}
      postBuild:
        {{- .postBuild | toYaml | nindent 6 }}
      {{- end }}
      prune: {{ .prune }}
      sourceRef:
        kind: GitRepository
        name: "{{ .source_name }}"
      {{- if $globalScope.Values.sopsEncryption.enabled }}
      decryption:
        provider: sops
        secretRef:
          name: "{{ $globalScope.Release.Name }}-sops-gpg"
      {{- end }}
    ---
    apiVersion: notification.toolkit.fluxcd.io/v1beta1
    kind: Alert
    metadata:
      name: "{{ .name }}-github-alert"
      namespace: "{{ $globalScope.Release.Namespace }}"
    spec:
      providerRef:
        name: "{{ .source_name }}-github-notification-provider"
      eventSeverity: info
      eventSources:
      - kind: Kustomization
        name: "{{ .name }}"
        namespace: "{{ $globalScope.Release.Namespace }}"
{{- end }}
