{{ $globalScope := . }}
{{- range .Values.sources }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crInstall" $globalScope }}-source-{{ .name }}
  namespace: {{ $globalScope.Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    # TODO
    "helm.sh/hook-weight": "6"
    {{- include "crInstallAnnotations" $globalScope | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "crInstall" $globalScope | quote }}
    {{- include "labels.selector" $globalScope | nindent 4 }}
    role: {{ include "crInstallSelector" $globalScope | quote }}
data:
  content: |
    ---
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    metadata:
      name: "{{ .name }}"
      namespace: "{{ $globalScope.Release.Namespace }}"
    spec:
      interval: "{{ .interval }}"
      ref:
        branch: "{{ .branch }}"
      secretRef:
        name: "{{ .name }}-credentials"
        namespace: "{{ $globalScope.Release.Namespace }}"
      url: "{{ .url }}"
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ .name }}-credentials"
      namespace: "{{ $globalScope.Release.Namespace }}"
    type: Opaque
    data:
      username: "{{ .credentials.username | b64enc }}"
      password: "{{ .credentials.password | b64enc }}"
      token: "{{ .credentials.password | b64enc }}"
    ---
    apiVersion: notification.toolkit.fluxcd.io/v1beta1
    kind: Provider
    metadata:
      name: "{{ .name }}-github-notification-provider"
      namespace: "{{ $globalScope.Release.Namespace }}"
    spec:
      type: {{ .provider }}
      address: "{{ .url | trimSuffix ".git" }}"
      secretRef:
        name: "{{ .name }}-credentials"
{{- end }}
