{{/*- if le (atoi (.Capabilities.KubeVersion.Minor | replace "+" "")) 24 */}}
# PSP were removed in k8s 1.25
# but we still require them in older versions
{{- if not .Values.global.podSecurityStandards.enforced }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  {{- if ge (int .Capabilities.KubeVersion.Minor) 19 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "runtime/default"
  {{- end }}
  labels:
    giantswarm.io/kustomize-selector: remove-psp
    {{ include "labels.common" . | nindent 4}}
  name: {{ printf "%s-pvc-psp" (include "name" .) | quote }}
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  volumes:
    - emptyDir
    - secret
{{- end }}
