{{- if not .Values.global.podSecurityStandards.enforced }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    giantswarm.io/service_type: managed
    helm.sh/chart: {{ include "chart" . }}
  name: flux-psp
rules:
  - apiGroups:
      - policy
    resourceNames:
      - {{ printf "%s-pvc-psp" (include "name" .) }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    giantswarm.io/service_type: managed
    helm.sh/chart: {{ include "chart" . }}
  name: crd-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-psp
subjects:
  - kind: ServiceAccount
    name: kustomize-controller
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: helm-controller
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: source-controller
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: notification-controller
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: image-reflector-controller
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: image-automation-controller
    namespace: {{ .Release.Namespace }}}
{{- end }}
