{{/*- if le (atoi (.Capabilities.KubeVersion.Minor | replace "+" "")) 24 */}}
{{- if not .Values.global.podSecurityStandards.enforced }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    giantswarm.io/kustomize-selector: remove-psp
    {{ include "labels.common" . | nindent 4}}
  name: "psp-{{ .Release.Name }}"
rules:
  - apiGroups:
      - policy
    resourceNames:
      - {{ .Release.Name }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    giantswarm.io/kustomize-selector: remove-psp
    {{ include "labels.common" . | nindent 4}}
  name: "psp-{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: kustomize-controller
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: helm-controller
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: source-controller
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: notification-controller
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: image-reflector-controller
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: image-automation-controller
    namespace: {{ .Release.Namespace }}}
{{- end }}
