{{ if not (lookup "v1" "Namespace" "" "policy-exceptions") -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: policy-exceptions
{{- end }}
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: flux-app
  namespace: policy-exceptions
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
spec:
  background: true
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
    - autogen-cronjob-host-path
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
    - autogen-cronjob-run-as-non-root
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
    - autogen-cronjob-restricted-volumes
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - adding-capabilities-strict
    - autogen-require-drop-all
    - autogen-cronjob-require-drop-all
    - autogen-adding-capabilities-strict
    - autogen-cronjob-adding-capabilities-strict
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        - Job
        names:
          - "helm-controller*"
          - "image-automation-controller*"
          - "image-reflector-controller*"
          - "kustomize-controller*"
          - "notification-controller*"
          - "source-controller*"
          - "flux-app-crd-install*"
        namespaces:
        - "{{ .Release.Namespace }}"
