{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Release.Name  }}-monitoring
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: {{ .Values.upstreamMetricsPort }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Release.Name  }}-monitoring
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
      port: http
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/name: {{ include "name" . }}
{{- end }}
