{{- if .Values.sopsEncryption.enabled }}
apiVersion: v1
data:
{{- range $index, $key := .Values.sopsEncryption.encryptionKeys }}
  "sops-{{ $index }}.asc": "{{ $key | b64enc }}"
{{- end }}
kind: Secret
metadata:
  name: "{{ .Release.Name }}-sops-gpg"
  namespace: "{{ .Release.Namespace }}"
---
{{- end }}
{{- range .Values.sources }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: "{{ .name }}"
  namespace: "{{ $.Release.Namespace }}"
spec:
  interval: "{{ .interval }}"
  ref:
    branch: "{{ .branch }}"
  secretRef:
    name: "{{ .name }}-credentials"
  url: "{{ .url }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .name }}-credentials"
  namespace: "{{ $.Release.Namespace }}"
type: Opaque
data:
  ## HTTP authentication to the repository (using a github token). Used by GitRepository.
  username: "{{ .credentials.username | default "" | b64enc }}"
  password: "{{ .credentials.password | default "" | b64enc }}"
  {{- if .credentials.ssh }}
  ## SSH authentication to the repository (using a github deploy key). Used by GitRepository.
  identity: "{{ .credentials.ssh.identity | default "" | b64enc }}"
  identity.pub: "{{ .credentials.ssh.identityPub | default "" | b64enc }}"
  known_hosts: "{{ .credentials.ssh.knownHosts | default "" | b64enc }}"
  {{- end }}
  ## Webhook token to be used by the receiver. Used by Receiver.
  token: "{{ .credentials.token | default "" | b64enc }}"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: "{{ .name }}-github-notification-provider"
  namespace: "{{ $.Release.Namespace }}"
spec:
  type: {{ .provider }}
  address: "{{ .url | trimSuffix ".git" }}"
  secretRef:
    name: "{{ .name }}-credentials"
{{- end }}
{{- range .Values.kustomizations }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: "{{ .name }}"
  namespace: "{{ $.Release.Namespace }}"
spec:
  interval: "{{ .interval }}"
  path: "{{ .path }}"
  prune: {{ .prune }}
  sourceRef:
    kind: GitRepository
    name: "{{ .source_name }}"
{{- if $.Values.sopsEncryption.enabled }}
  decryption:
    provider: sops
    secretRef:
      name: "{{ $.Release.Name }}-sops-gpg"
{{- end }}
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: "{{ .name }}-github-alert"
  namespace: "{{ $.Release.Namespace }}"
spec:
  providerRef:
    name: "{{ .source_name }}-github-notification-provider"
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "{{ .name }}"
      namespace: "{{ $.Release.Namespace }}"
{{- end }}
