{{- if .Values.sopsEncryption.enabled }}
apiVersion: v1
data:
{{- range $index, $key := .Values.sopsEncryption.encryptionKeys }}
  "sops-{{ $index }}.asc": "{{ $key | b64enc }}"
{{- end }}
kind: Secret
metadata:
  name: "{{ .Release.Name }}-sops-gpg"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "0"
    {{- include "fluxResourceInstallAnnotations" . | nindent 4 }}
---
{{- end }}
{{- range .Values.sources }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: "{{ .name }}"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "1"
    {{- include "fluxResourceInstallAnnotations" . | nindent 4 }}
spec:
  interval: "{{ .interval }}"
  ref:
    branch: "{{ .branch }}"
  secretRef:
    name: "{{ .name }}-credentials"
  url: "{{ .url }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .name }}-credentials"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "0"
    {{- include "fluxResourceInstallAnnotations" . | nindent 4 }}
type: Opaque
data:
  username: "{{ .credentials.username | b64enc }}"
  password: "{{ .credentials.password | b64enc }}"
  token: "{{ .credentials.password | b64enc }}"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: "{{ .name }}-github-notification-provider"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "1"
    {{- include "fluxResourceInstallAnnotations" . | nindent 4 }}
spec:
  type: github
  address: "{{ .url | trimSuffix ".git" }}"
  secretRef:
    name: "{{ .name }}-credentials"
{{- end }}
{{- range .Values.kustomizations }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: "{{ .name }}"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "2"
    {{- include "fluxResourceInstallAnnotations" . | nindent 4 }}
spec:
  interval: "{{ .interval }}"
  path: "{{ .path }}"
  prune: {{ .prune }}
  sourceRef:
    kind: GitRepository
    name: "{{ .source_name }}"
  validation: client
{{- if $.Values.sopsEncryption.enabled }}
  decryption:
    provider: sops
    secretRef:
      name: "{{ $.Release.Name }}-sops-gpg"
{{- end }}
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: "{{ .name }}-github-alert"
  namespace: "{{ $.Release.Namespace }}"
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "3"
    {{- include "fluxResourceInstallAnnotations" . | nindent 4 }}
spec:
  providerRef:
    name: "{{ .source_name }}-github-notification-provider"
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "{{ .name }}"
      namespace: "{{ $.Release.Namespace }}"
{{- end }}
