images:
  registry: quay.io
  helmController:
    image: giantswarm/fluxcd-helm-controller
    version: v0.11.0
  sourceController:
    image: giantswarm/fluxcd-source-controller
    version: v0.14.0
  kustomizeController:
    image: giantswarm/fluxcd-kustomize-controller
    version: v0.13.0
  notificationController:
    image: giantswarm/fluxcd-notification-controller
    version: v0.15.0
  imageAutomationController:
    image: giantswarm/fluxcd-image-automation-controller
    version: v0.12.0
  imageReflectorController:
    image: giantswarm/fluxcd-image-reflector-controller
    version: v0.10.0

# only GitRepository for now
sources: []
kustomizations: []

sopsEncryption:
  enabled: false
  encryptionKeys: []

crds:
  install: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

# allows to change the persistentVolumeClaim request sizes
volumes:
  helmController:
    temp:
      size: 100Mi
  imageAutomationController:
    temp:
      size: 100Mi
  imageReflectorController:
    temp:
      size: 100Mi
    data:
      size: 100Mi
  kustomizeController:
    temp:
      size: 100Mi
  notificationController:
    temp:
      size: 100Mi
  sourceController:
    temp:
      size: 100Mi
    data:
      size: 100Mi
