images:
  registry: quay.io
  helm_controller:
    image: giantswarm/fluxcd-helm-controller
  source_controller:
    image: giantswarm/fluxcd-source-controller
  kustomize_controller:
    image: giantswarm/fluxcd-kustomize-controller
  notification_controller:
    image: giantswarm/fluxcd-notification-controller
  image_automation_controller:
    image: giantswarm/fluxcd-image-automation-controller
  image_reflector_controller:
    image: giantswarm/fluxcd-image-reflector-controller

# only GitRepository for now
sources: []
kustomizations: []

sopsEncryption:
  enabled: false
  encryptionKey: ""

crds:
  install: true
