images:
  registry: quay.io
  helm_controller:
    image: giantswarm/fluxcd-helm-controller
    tag: v0.4.1
  source_controller:
    image: giantswarm/fluxcd-source-controller
    tag: v0.4.1
  kustomize_controller:
    image: giantswarm/fluxcd-kustomize-controller
    tag: v0.4.0
  notification_controller:
    image: giantswarm/fluxcd-notification-controller
    tag: v0.4.0
