images:
  registry: docker.io
  helmController:
    image: giantswarm/fluxcd-helm-controller
  sourceController:
    image: giantswarm/fluxcd-source-controller
  kustomizeController:
    image: giantswarm/fluxcd-kustomize-controller
  notificationController:
    image: giantswarm/fluxcd-notification-controller
  imageAutomationController:
    image: giantswarm/fluxcd-image-automation-controller
  imageReflectorController:
    image: giantswarm/fluxcd-image-reflector-controller

# allows to change cluster related configurations
cluster:
  domain: cluster.local

# only GitRepository for now
sources: []

# Kustomizations Example
#
# kustomizations:
# - name: my-kustomization
#   source_name: my-git-source
#   path: ./the-path
#   postBuild:
#     substitute:
#       environment: "my-env"
#     substituteFrom:
#       - kind: ConfigMap
#         name: my-env-vars
#   prune: false
#   interval: 10m0s
#
kustomizations: []

sopsEncryption:
  enabled: false
  encryptionKeys: []

crds:
  install: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

resources:
  helmController:
    limits:
      cpu: 500m
      # Set max allowed memory limit for VPA due to high memory usage.
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
  imageAutomationController:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
  imageReflectorController:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
  kustomizeController:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
  notificationController:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
  sourceController:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

upstreamMetricsPort: http-prom

# allows VPA to be used if its installed in the cluster
verticalPodAutoscaler:
  enabled: false
  # enables bypassing "autoscaling.k8s.io/v1" check; use with care
  force: false

# allows to change the persistentVolumeClaim request sizes
volumes:
  helmController:
    temp:
      size: 100Mi
  imageAutomationController:
    temp:
      size: 100Mi
  imageReflectorController:
    temp:
      size: 100Mi
    data:
      size: 100Mi
  kustomizeController:
    temp:
      size: 100Mi
  notificationController:
    temp:
      size: 100Mi
  sourceController:
    temp:
      size: 100Mi
    data:
      size: 100Mi

# Annotations to add on to the kustomize controller service account
# Allows for adding custom annotations such as those required for use of
# KMS keys.
kustomizeServiceAccount:
  annotations: {}
