images:
  registry: docker.io
  helmController:
    image: giantswarm/fluxcd-helm-controller
  sourceController:
    image: giantswarm/fluxcd-source-controller
  kustomizeController:
    image: giantswarm/fluxcd-kustomize-controller
  notificationController:
    image: giantswarm/fluxcd-notification-controller
  imageAutomationController:
    image: giantswarm/fluxcd-image-automation-controller
  imageReflectorController:
    image: giantswarm/fluxcd-image-reflector-controller

# only GitRepository for now
sources: []
kustomizations: []

sopsEncryption:
  enabled: false
  encryptionKeys: []

crds:
  install: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

# allows to change the persistentVolumeClaim request sizes
volumes:
  helmController:
    temp:
      size: 100Mi
  imageAutomationController:
    temp:
      size: 100Mi
  imageReflectorController:
    temp:
      size: 100Mi
    data:
      size: 100Mi
  kustomizeController:
    temp:
      size: 100Mi
  notificationController:
    temp:
      size: 100Mi
  sourceController:
    temp:
      size: 100Mi
    data:
      size: 100Mi
