images:
  registry: quay.io
  helmController:
    image: giantswarm/fluxcd-helm-controller
  sourceController:
    image: giantswarm/fluxcd-source-controller
  kustomizeController:
    image: giantswarm/fluxcd-kustomize-controller
  notificationController:
    image: giantswarm/fluxcd-notification-controller
  imageAutomationController:
    image: giantswarm/fluxcd-image-automation-controller
  imageReflectorController:
    image: giantswarm/fluxcd-image-reflector-controller

# only GitRepository for now
sources: []
kustomizations: []

sopsEncryption:
  enabled: false
  encryptionKeys: []

crds:
  install: true
