apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "controllerVolumeName" (merge (dict "volumeName" "helm-controller-temp") .) | quote }}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      #storage: '{{ .Values.volumes.helmControllerTemp.size | quote }}'
      storage: 100Mi
