apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: helm-controller
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: manager
      controlledValues: RequestsAndLimits
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  helm-controller
  updatePolicy:
    updateMode: Auto
