apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "controllerVolumeName" (merge (dict "volumeName" "image-automation-controller-temp") .) | quote }}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
