apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "controllerVolumeName" (merge (dict "volumeName" "image-reflector-controller-temp") .) | quote }}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100MiB
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "controllerVolumeName" (merge (dict "volumeName" "image-reflector-controller-data") .) | quote }}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100MiB
