apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "controllerVolumeName" (merge (dict "volumeName" "kustomize-controller-temp") .) | quote }}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '{{ .Values.volumes.kustomizeController.temp.size | quote }}'
