apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: '{{ include "name" . }}-pvc-psp'
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    rule: MustRunAsNonRoot
  volumes:
  - 'persistentVolumeClaim'
