apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: '{{ printf "%s-pvc-psp" (include "name" .) | quote }}'
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    rule: MustRunAsNonRoot
  volumes:
  - 'persistentVolumeClaim'
