apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "controllerVolumeName" (merge (dict "volumeName" "source-controller-temp") .) }}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '{{ .Values.volumes.sourceController.temp.size }}'
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "controllerVolumeName" (merge (dict "volumeName" "source-controller-data") .) }}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '{{ .Values.volumes.sourceController.data.size }}'
  storageClassName: ""
